# Generated by Django 4.0.3 on 2022-04-08 10:54

import BRDAdmin.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BRDAdmin', '0004_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', BRDAdmin.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
