# Generated by Django 4.0.3 on 2022-04-09 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BRDAdmin', '0005_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BRDAdmin.role'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='usertype',
            field=models.CharField(blank=True, choices=[('Salesman', 'Salesman'), ('Evaluator', 'Evaluator'), ('Callcentre', 'callcentre'), ('Admin', 'Admin')], max_length=20, null=True),
        ),
    ]
