# Generated by Django 4.0.3 on 2022-04-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BRDAdmin', '0006_alter_customuser_district_alter_customuser_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('Created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Brand',
                'ordering': ['-Created_at'],
            },
        ),
    ]
