# Generated by Django 4.0.3 on 2022-04-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BRDAdmin', '0007_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('Created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Color',
                'ordering': ['-Created_at'],
            },
        ),
    ]
